// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkWA40mzzucPxzyRIMSDDIWYmIW6heRQ',
    appId: '1:480334582103:web:1751b8486560db5edcee12',
    messagingSenderId: '480334582103',
    projectId: 'fluuter-app-jam-app',
    authDomain: 'fluuter-app-jam-app.firebaseapp.com',
    storageBucket: 'fluuter-app-jam-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQD2dOhIVsCms-UgYmvcvgmBXwiSm4vQ',
    appId: '1:480334582103:android:639f748f4a416c7adcee12',
    messagingSenderId: '480334582103',
    projectId: 'fluuter-app-jam-app',
    storageBucket: 'fluuter-app-jam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xOSo-4ywFRsQMbcr_J2JMycyVByUXIE',
    appId: '1:480334582103:ios:9569d8fb2b11217ddcee12',
    messagingSenderId: '480334582103',
    projectId: 'fluuter-app-jam-app',
    storageBucket: 'fluuter-app-jam-app.appspot.com',
    iosBundleId: 'com.example.flutterAppJamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1xOSo-4ywFRsQMbcr_J2JMycyVByUXIE',
    appId: '1:480334582103:ios:5f5064cc1c334b99dcee12',
    messagingSenderId: '480334582103',
    projectId: 'fluuter-app-jam-app',
    storageBucket: 'fluuter-app-jam-app.appspot.com',
    iosBundleId: 'com.example.flutterAppJamApp.RunnerTests',
  );
}
